In [2]:
import numpy as np

In [4]:
# 1차원 인덱싱
arr = np.arange(1, 10)
print(arr)
print(arr[5])
print(arr[-1])
print(arr[0:4])
print(arr[:])
print(arr > 7)
print(arr[arr>7])
print(arr[~(arr>7)])

[1 2 3 4 5 6 7 8 9]
6
9
[1 2 3 4]
[1 2 3 4 5 6 7 8 9]
[False False False False False False False  True  True]
[8 9]
[1 2 3 4 5 6 7]
